django_serials/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('', include('serials.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

serials/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.SerialsView.as_view()),
    path('filter/', views.FilterSerialsView.as_view(), name='filter'),
    path('search/', views.Search.as_view(), name='search'),
    path('json-filter/', views.JsonFilterSerialsView.as_view(), name='json_filter'),
    path('add-rating/', views.AddStarRating.as_view(), name='add_rating'),
    path("<slug:slug>/", views.SerialDetailView.as_view(), name='serial_detail'),
    path('review/<int:pk>/', views.AddReview.as_view(), name='add_review'),
    path('actor/<str:slug>/', views.ActorView.as_view(), name='actor_detail'),
]

serials/models.py
from django.db import models
from datetime import date
from django.urls import reverse


# Create your models here.


class Category(models.Model):
    # Категории
    name = models.CharField('Категория', max_length=150)
    description = models.TextField('Описание')
    url = models.SlugField(max_length=160, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'


class Actor(models.Model):
    # Актеры и режиссеры
    name = models.CharField('Имя', max_length=100)
    age = models.PositiveIntegerField('Возраст', default=0)
    description = models.TextField('Описание')
    image = models.ImageField('Изображение', upload_to='actors/')

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('actor_detail', kwargs={'slug': self.name})

    class Meta:
        verbose_name = 'Актер'
        verbose_name_plural = 'Актеры'


class Genre(models.Model):
    # Жанры
    name = models.CharField('Имя', max_length=100)
    description = models.TextField('Описание')
    url = models.SlugField(max_length=160, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Жанр'
        verbose_name_plural = 'Жанры'


class Serial(models.Model):
    # Сериалы
    title = models.CharField('Название', max_length=100)
    description = models.TextField('Описание')
    poster = models.ImageField('Постер', upload_to='serials/')
    year = models.PositiveIntegerField('Дата выхода', default=2000)
    country = models.CharField('Страна', max_length=100)
    # director = models.ManyToManyField(Actor, verbose_name='режиссер', related_name='film_director')
    actors = models.ManyToManyField(Actor, verbose_name='актеры', related_name='film_actor')
    genres = models.ManyToManyField(Genre, verbose_name='жанры')
    world_premiere = models.DateField('Премьера в мире', default=date.today)
    seasons = models.PositiveSmallIntegerField('Сезонов')
    series = models.PositiveSmallIntegerField('Серий')
    category = models.ForeignKey(Category, verbose_name='Категория', on_delete=models.SET_NULL, null=True)
    url = models.SlugField(max_length=160, unique=True)
    draft = models.BooleanField('Черновик', default=False)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('serial_detail', kwargs={'slug': self.url})

    def get_review(self):
        return self.reviews_set.filter(parent__isnull=True)

    class Meta:
        verbose_name = 'Сериал'
        verbose_name_plural = 'Сериалы'


class SerialShots(models.Model):
    title = models.CharField('Заголовок', max_length=100)
    description = models.TextField('Описание')
    image = models.ImageField('Изображение', upload_to='serial_shots/')
    serial = models.ForeignKey(Serial, verbose_name='Сериал', on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Кадр'
        verbose_name_plural = 'Кадры'


class RatingStar(models.Model):
    value = models.SmallIntegerField('Значение', default=0)

    def __str__(self):
        return f'{self.value}'

    class Meta:
        verbose_name = 'Звезда рейтинга'
        verbose_name_plural = 'Звезды рейтинга'
        ordering = ["-value"]


class Rating(models.Model):
    ip = models.CharField('IP адрес', max_length=15)
    star = models.ForeignKey(RatingStar, on_delete=models.CASCADE, verbose_name='звезда')
    serial = models.ForeignKey(Serial, on_delete=models.CASCADE, verbose_name='сериал')

    def __str__(self):
        return f'{self.star} - {self.serial}'

    class Meta:
        verbose_name = 'Рейтинг'
        verbose_name_plural = 'Рейтинг'


class Reviews(models.Model):
    email = models.EmailField()
    name = models.CharField('Название', max_length=100)
    text = models.TextField('Сообщение', max_length=1000)
    parent = models.ForeignKey('self', verbose_name='Родитель', on_delete=models.SET_NULL, blank=True, null=True)
    serial = models.ForeignKey(Serial, on_delete=models.CASCADE, verbose_name='сериал')

    def __str__(self):
        return f'{self.name} - {self.serial}'

    class Meta:
        verbose_name = 'Отзыв'
        verbose_name_plural = 'Отзывы'

serials/forms.py
from django import forms

from .models import Reviews, Rating, RatingStar


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Reviews
        fields = ('name', 'email', 'text')


class RatingForm(forms.ModelForm):

    star = forms.ModelChoiceField(
        queryset=RatingStar.objects.all(), widget=forms.RadioSelect(), empty_label=None
    )

    class Meta:
        model = Rating
        fields = ('star',)

serials/views.py
from django.db.models import Q
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView
from django.views.generic.base import View

from .models import Serial, Category, Actor, Genre, Rating
from .forms import ReviewForm, RatingForm


class GenreYear:

    def get_genres(self):
        return Genre.objects.all()

    def get_years(self):
        return Serial.objects.filter(draft=False).values('year')


class SerialsView(GenreYear, ListView):
    model = Serial
    queryset = Serial.objects.filter(draft=False).order_by('-year')
    paginate_by = 6
    # template_name = 'serials/serial_list.html'

    # def get_context_data(self, *args, **kwargs):
    #     context = super().get_context_data(*args, **kwargs)
    #     context['categories'] = Category.objects.all()
    #     return context


class SerialDetailView(GenreYear, DetailView):
    model = Serial
    queryset = Serial.objects.filter(draft=False)
    slug_field = 'url'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['star_form'] = RatingForm()
        return context


class AddReview(View):

    def post(self, request, pk):
        form = ReviewForm(request.POST)
        serial = Serial.objects.get(id=pk)
        if form.is_valid():
            form = form.save(commit=False)
            if request.POST.get('parent', None):
                form.parent_id = int(request.POST.get('parent'))
            form.serial = serial
            form.save()
        return redirect(serial.get_absolute_url())


class ActorView(GenreYear, DetailView):

    model = Actor
    template_name = 'serials/actor.html'
    slug_field = 'name'


class FilterSerialsView(GenreYear, ListView):

    paginate_by = 2

    def get_queryset(self):
        queryset = Serial.objects.filter(
            Q(year__in=self.request.GET.getlist('year')) |
            Q(genres__in=self.request.GET.getlist('genre'))
        ).distinct()
        return queryset

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['year'] = ''.join([f'year={x}&' for x in self.request.GET.getlist('year')])
        context['genre'] = ''.join([f'year={x}&' for x in self.request.GET.getlist('genre')])
        return context


class JsonFilterSerialsView(ListView):

    def get_queryset(self):
        queryset = Serial.objects.filter(
            Q(year__in=self.request.GET.getlist("year")) |
            Q(genres__in=self.request.GET.getlist("genre"))
        ).distinct().values("title", "url", "poster")
        return queryset

    def get(self, request, *args, **kwargs):
        queryset = list(self.get_queryset())
        return JsonResponse({"serials": queryset}, safe=False)


class AddStarRating(View):

    def get_client_ip(self, request):
        x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
        if x_forwarded_for:
            ip = x_forwarded_for.split(',')[0]
        else:
            ip = request.META.get('REMOTE_ADDR')
        return ip

    def post(self, request):
        form = RatingForm(request.POST)
        if form.is_valid():
            Rating.objects.update_or_create(
                ip=self.get_client_ip(request),
                serial_id=int(request.POST.get('serial')),
                defaults={'star_id': int(request.POST.get('star'))}
            )
            return HttpResponse(status=201)
        else:
            return HttpResponse(status=400)


class Search(ListView):

    paginate_by = 2

    def get_queryset(self):
        q = self.request.GET.get('q').capitalize()
        return Serial.objects.filter(title__icontains=q)

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['q'] = f"q={self.request.GET.get('q')}&"
        return context

templates/serials/actor.html
{% extends 'serials/base.html' %}

{% load static %}

{% block banner %}bg3 {% endblock banner %}

{% block container %}
    <div class="container py-md-3">
{% endblock container %}

{% block sidebar %}
    <div class="side-bar col-lg-3">
        {% include 'include/sidebar.html' %}
    </div>
{% endblock sidebar %}

{% block serial %}
    <div class="left-ads-display col-lg-8">
        <div class="row">
            <div class="desc1-left col-md-6">
                <img src="{{ actor.image.url }}" class="img-fluid" alt="">
            </div>
            <div class="desc1-right col-md-6 pl-lg-4">
                <h3 class="editContent">
                    {{ actor.name }}
                </h3>
<!--                <h5 class="editContent">Terminator: Dark Fate</h5>-->
                <ul>
                    <li>
                        <span><b>Возраст:</b> {{ actor.age }} лет </span>
                    </li>
                    <li>
                        <span><b>Актер:</b>
                            {% for serial in actor.film_actor.all %}
                                {{ serial.title }}
                            {% endfor %}
                        </span>
                    </li>
                </ul>
            </div>
        </div>
        <div class="row sub-para-w3layouts mt-5">
            <h3 class="shop-sing editContent">
                О {{ actor.name }}
            </h3>
            <p class="edtContent">
                {{ actor.description }}
            </p>
        </div>


    </div>
{% endblock serial %}

templates/serials/base.html
{% extends 'base.html' %}

{% block content %}
    <section class="ab-info-main py-md-5 py-4 editContent" style="padding-left: 3rem; padding-right: 3rem;">
        {% block container %}
        <div class="container-fluid py-md-3">
        {% endblock container %}
            <div class="row">
                {% block sidebar %}
                    <div class="side-bar col-lg-3">
                        {% include 'include/sidebar.html' %}
                    </div>
                {% endblock sidebar %}
                    {% block serial %}

                    {% endblock serial %}
            </div>
        </div>
    </section>
{% endblock content %}

templates/serials/serial_detail.html
{% extends 'serials/base.html' %}

{% load static %}

{% block banner %}{% endblock banner %}

{% block container %}
    <div class="container py-md-3">
{% endblock container %}

{% block sidebar %}
    <div class="side-bar col-lg-3">
        {% include 'include/sidebar.html' %}
    </div>
{% endblock sidebar %}

{% block serial %}
    <div class="left-ads-display col-lg-8">
        <div class="row">
            <div class="desc1-left col-md-6">
                <img src="{{ serial.poster.url }}" class="img-fluid" alt="">
            </div>
            <div class="desc1-right col-md-6 pl-lg-4">
                <h3 class="editContent" style="outline: none; cursor: inherit;">
                    {{ serial.title }}
                </h3>
                <h5 class="editContent"></h5>
                <ul>
                    <li style="list-style: none"><span><b>Год:</b> {{ serial.year }}</span></li>
                    <li style="list-style: none"><span><b>Страна:</b> {{ serial.country }}</span>
                    </li>
                    <li style="list-style: none"><span><b>Серий:</b> {{ serial.series }}</span>
                    </li>
                    <li style="list-style: none">
                        <span><b>Сезонов:</b> {{ serial.seasons }}</span></li>
                    <li style="list-style: none"><span><b>Актеры:</b>
                        {% for actor in serial.actors.all %}
                            <a href="{{ actor.get_absolute_url }}">
                               {{ actor.name }}
                            </a>
                        {% endfor %}
                    </span></li>
                    <li style="list-style: none"><span><b>Жанр:</b>
                        {% for genre in serial.genres.all %}
                            {{ genre.name }}
                        {% endfor %}</span>
                    </li>
                    <li style="list-style: none"><span><b>Премьера в мире:</b> {{ serial.world_premiere }}</span>
                    </li><!--
                    <li style="list-style: none">
                        <span><b>Бюджет:</b> $185 000 000</span></li>
                    <li style="list-style: none">
                        <span><b>Сборы в США:</b> $61 150 256</span></li>
                    <li style="list-style: none"><span><b>Сборы в мире:</b> $250 369 693</span>
                    </li>-->
                    <li><!--style="list-style: none"-->
                        <form action="{% url 'add_rating' %}" method="post" name="rating">
                            <b>Рейтинг:</b>
                            {% csrf_token %}
<!--                            <input type="hidden" value="{{ request.path }}" name="next">-->
                            <input type="hidden" value="{{ serial.id }}" name="serial">
                            <span class="rating">
                                {% for k, v in star_form.fields.star.choices %}
                                    <input id="rating{{ v }}" type="radio" name="star" value="{{ k }}">
                                    <label for="rating{{ v }}">{{ k }}</label>
                                {% endfor %}
                            </span>
                            <span class="editContent">4.0</span>
<!--                                <span class="fa fa-star" aria-hidden="true"-->
<!--                                      style="outline: none; cursor: inherit;"></span>-->
<!--                                <span class="fa fa-star" aria-hidden="true"-->
<!--                                      style="outline: none; cursor: inherit;"></span>-->
<!--                                <span class="fa fa-star" aria-hidden="true"-->
<!--                                      style="outline: none; cursor: inherit;"></span>-->
<!--                                <span class="fa fa-star" aria-hidden="true"-->
<!--                                      style="outline: none; cursor: inherit;"></span>-->
<!--                                <span class="fa fa-star" aria-hidden="true"-->
<!--                                      style="outline: none; cursor: inherit;"></span>-->
<!--                                <span class="editContent"-->
<!--                                      style="outline: none; cursor: inherit;">5.0</span>-->

                        </form>
                    </li>
                    <div class="share-desc">
                        <div class="share">
                            <h4 class="editContent"
                                style="outline: none; cursor: inherit;">
                                Share:</h4>
                            <ul class="w3layouts_social_list list-unstyled">
                                <li>
                                    <a href="#" class="w3pvt_facebook editContent"
                                       style="outline: none; cursor: inherit;">
                                    <span class="fa fa-facebook-f"
                                          style="outline: none; cursor: inherit;"></span>
                                    </a>
                                </li>
                                <li>
                                    <a href="#" class="w3pvt_twitter editContent"
                                       style="outline: none; cursor: inherit;">
                                    <span class="fa fa-twitter"
                                          style="outline: none; cursor: inherit;"></span>
                                    </a>
                                </li>
                                <li>
                                    <a href="#" class="w3pvt_dribble editContent"
                                       style="outline: none; cursor: inherit;">
                                    <span class="fa fa-dribbble"
                                          style="outline: none; cursor: inherit;"></span>
                                    </a>
                                </li>
                            </ul>
                        </div>
                        <div class="clearfix"></div>
                    </div>
                </ul>
            </div>
        </div>
        <div class="row sub-para-w3layouts mt-5">

            <h3 class="shop-sing editContent">
                О сериале {{ serial.title }}</h3>
            <p>

                {% for image in serial.serialshots_set.all %}
                <img src="{{ image.image.url }}" class="img-serial-shots" alt="{{ image.descripion }}">
                {% endfor %}
            </p>
            <p class="editContent">
                {{ serial.description|safe }}
            </p>
        </div>
        <hr>
        <div class="row">
            <div class="single-form-left">
                <!-- contact form grid -->
                <div class="contact-single">
                    <h3 class="editContent">
                        <span class="sub-tittle editContent">{{ serial.reviews_set.count }}</span>Оставить отзыв</h3>
                    <form action="{% url 'add_review' serial.id %}" method="post" class="mt-4" id="formReview">
                        {% csrf_token %}
                        <input type="hidden" name="parent" id="contactparent" value="">
                        <div class="form-group editContent">
                            <label for="contactcomment" class="editContent">
                                Ваш комментарий*
                            </label>
                            <textarea class="form-control border" rows="5" name="text"
                                      id="contactcomment" required=""></textarea>
                        </div>
                        <div class="d-sm-flex">
                            <div class="col-sm-6 form-group p-0 editContent">
                                <label for="contactusername" class="editContent">
                                    Имя *
                                </label>
                                <input type="text" class="form-control border" name="name"
                                       id="contactusername" required="">
                            </div>
                            <div class="col-sm-6 form-group ml-sm-3 editContent">
                                <label for="contactemail" class="editContent">
                                    Email *
                                </label>
                                <input type="email" class="form-control border" name="email"
                                       id="contactemail" required="">
                            </div>
                        </div>
                        <button type="submit"
                                class="mt-3 btn btn-success btn-block py-3">
                            Отправить
                        </button>
                    </form>
                </div>
                <!--  //contact form grid ends here -->
            </div>
            {% for review in serial.get_review %}
            <div class="media py-5">
                <img src="{% static 'images/te2.jpg' %}" class="mr-3 img-fluid" alt="image">
                <div class="media-body mt-4">
                    <h5 class="mt-0 editContent">
                        {{ review.name }}
                    </h5>
                    <p class="mt-2 editContent">
                        {{ review.text }}
                    </p>
                    <a href="#formReview" onclick="addReview('{{ review.name}}', '{{ review.id }}')">Ответить</a>
                    {% for rew in review.reviews_set.all %}
                        <div class="media mt-5 editContent">
                            <a class="pr-3" href="#">
                                <img src="{% static 'images/te1.jpg' %}" class="img-fluid " alt="image">
                            </a>
                            <div class="media-body">
                                <h5 class="mt-0 editContent">{{ rew.name }}</h5>
                                <p class="mt-2 editContent">{{ rew.text }}</p>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
    <script>
        function addReview(name, id) {
            document.getElementById('contactparent').value = id;
            document.getElementById('contactcomment').innerText = `${name}, `.
        }
    </script>
{% endblock serial %}

templates/serials/serial_list.html
{% extends 'serials/base.html' %}

{% block banner %}bg1{% endblock banner %}

{% block serial %}
    <div class="left-ads-display col-lg-9">
        <div class="row">
            {% for serial in serial_list %}
                <div class="col-md-4 product-men">
                    <div class="product-shoe-info editContent text-center mt-lg-4">
                        <div class="men-thumb-item">
                            <img src="{{ serial.poster.url }}" class="img-fluid" alt="">
                        </div>
                        <div class="item-info-product">
                            <h4 class="">
                                <a href="{{ serial.get_absolute_url }}" class="editContent">{{ serial.title }}</a>
                            </h4>
                        </div>
                    </div>
            </div>
            {% endfor %}
        </div>
        <div class="grid-img-right mt-4 text-right bg bg1" >
            {% include 'include/pagination.html' %}
        </div>
    </div>
{% endblock serial %}